// quotePackage/pages/chooseProductFields/chooseProductFields.js
Page({
  data: {
    fields:[
      {
        name:'商品名称',
        ifChoose:true
      },
      {
        name:'商品编号',
        ifChoose:false
      },
      {
        name:'型号',
        ifChoose:false
      },
      {
        name:'参数',
        ifChoose:false
      },
      {
        name:'数量',
        ifChoose:false
      },
      {
        name:'单位',
        ifChoose:false
      },
      {
        name:'单价',
        ifChoose:false
      },
      {
        name:'品牌',
        ifChoose:false
      },
      {
        name:'生产厂商',
        ifChoose:false
      },
      {
        name:'产地',
        ifChoose:false
      },
      {
        name:'备注',
        ifChoose:false
      }
    ]
  },
  chooseField(e){
    const fields=this.data.fields
    fields[e.currentTarget.dataset.index].ifChoose=!fields[e.currentTarget.dataset.index].ifChoose
    this.setData({
      fields:fields
    })
  },
  cancel(){
    wx.navigateBack()
  },
  confirm(){
    wx.navigateBack()
  }
})